#!/bin/bash

LOG_FILE="myLog.log"

# Save original stdout to file descriptor 3
exec 3>&1

# Redirect all output (stdout and stderr) to LOG_FILE
exec >"$LOG_FILE" 2>&1

if [[ -f "$1" ]]; then
  echo "Debugging!!!!!"
  tsc
  node --inspect-brk=9229 build/cliClass.js "$1"
else
  echo "File not found: $1" >&3
fi
